# Generated by Django 5.1 on 2024-08-28 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='address',
            new_name='tour',
        ),
    ]
