# Generated by Django 5.1 on 2024-08-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_rename_address_booking_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='tour_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='tour_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='tour_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
